### ISSUE TITLE
Generated meta tag has double quotes on the end

### ISSUE THREAD

**Issue by PauliCZ44** [InBrowserApp/favicon.inbrowser.app#2]
Thanks for this app, it is awesome. Btw. design is slick.

I have found this issue. When i create something, last meta tag has double quotes likes this:

<meta name="theme-color" content="#401172"">

![image](https://github.com/InBrowserApp/favicon.inbrowser.app/assets/62062095/e317f487-e58a-46e2-9d54-4349d7f7a836)

**Comment by rwv** [comment]
thank you!
